<?php

  #The URL root is the AWS meta data service URL where metadata
  # requests regarding the running instance can be made
  $urlRoot="http://169.254.169.254/latest/meta-data/";

  # Get the instance ID from meta-data and print to the screen
  $instance = file_get_contents($urlRoot . 'instance-id');

  # Availability Zone
  $az = file_get_contents($urlRoot . 'placement/availability-zone');
?>
<?php
function stress (){
  $output = shell_exec('stress --cpu 8 --timeout 120 > output.txt &');
echo "<pre>$output</pre>";}
?>
<?php
if(array_key_exists('clickme',$_POST)){
    stress()
}
?>

<center>This page was generated by instance <b><?= $instance ?></b> in Availability Zone <b><?= $az ?></b>.</center>
  <form action="stress.php" method="get">
  <!--<input type="submit" value="Buy A lot">--> 
  <input type="submit" value="Buy A Lot!" name="clickme">
</form>